# Welcome to numpy

In [1]:
import numpy as np

In [2]:
arr = np.array([3,6,32,7])
arr

array([ 3,  6, 32,  7])

In [3]:
arr = np.array([3,6,32,7],np.int64)

In [4]:
arr[0]

3

In [5]:
arr = np.array([[3,6,32,7]],np.int64)
print(arr[0])
print(arr[0,1])

[ 3  6 32  7]
6


In [6]:
arr.shape

(1, 4)

In [7]:
arr.dtype

dtype('int64')

In [8]:
arr[0,2] = 65
arr

array([[ 3,  6, 65,  7]], dtype=int64)

# Array creation: Conversion from other Python structures

In [9]:
listarray = np.array([[1,2,3], [5,8,5], [0,3,1]])
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [10]:
listarray.dtype

dtype('int32')

In [11]:
listarray.shape

(3, 3)

In [12]:
listarray.size

9

In [13]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [14]:
z = np.zeros((2,5))

In [15]:
z.shape

(2, 5)

In [16]:
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
r = np.arange(15)
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
lspace = np.linspace(1,5,4)
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [19]:
emp = np.empty((4,6))
emp

array([[3.56043053e-307, 1.60219306e-306, 7.56571288e-307,
        1.89146896e-307, 1.37961302e-306, 1.05699242e-307],
       [8.01097889e-307, 1.78020169e-306, 7.56601165e-307,
        1.02359984e-306, 1.33510679e-306, 2.22522597e-306],
       [1.33511018e-306, 6.23057689e-307, 1.33511290e-306,
        1.78019082e-306, 8.45559303e-307, 8.06613465e-308],
       [6.89810244e-307, 1.22387550e-307, 2.22522596e-306,
        8.34423917e-308, 9.79107193e-307, 3.33509775e-317]])

In [20]:
emp_like = np.empty_like(lspace)
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [21]:
ide = np.identity(30)

In [22]:
ide.shape

(30, 30)

In [23]:
arr1 = np.arange(99)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [24]:
arr1.reshape(3,33) 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [25]:
arr1.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [26]:
arr1.shape

(99,)

In [27]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [28]:
ar.sum(axis=0)

array([12,  8,  9])

In [29]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [47]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [31]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [32]:
ar.ndim

2

In [33]:
ar.size

9

In [37]:
ar.nbytes

36

In [38]:
one = np.array([1,3,4,634,2])

In [40]:
one.argmax()

3

In [41]:
one.argmin()

0

In [44]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [48]:
ar.argmin()

8

In [49]:
ar.argmax()

6

In [51]:
 ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [52]:
 ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [53]:
 ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [54]:
 ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [56]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [60]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [65]:
ar2 = np.array(([[1, 2, 1],
                 [4, 5, 6],
                 [7,1, 0]]))

In [66]:
ar + ar2

array([[ 2,  4,  4],
       [ 8, 10, 12],
       [14,  2,  0]])

In [67]:
ar * ar2

array([[ 1,  4,  3],
       [16, 25, 36],
       [49,  1,  0]])

In [68]:
ar/ar2

C:\Users\Dell\AppData\Local\Temp/ipykernel_20004/2166607628.py:1: RuntimeWarning: invalid value encountered in true_divide
  ar/ar2


array([[ 1.,  1.,  3.],
       [ 1.,  1.,  1.],
       [ 1.,  1., nan]])

In [69]:
ar - ar2

array([[0, 0, 2],
       [0, 0, 0],
       [0, 0, 0]])

In [71]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [72]:
ar.sum() 

29

In [74]:
ar.max()

7

In [75]:
ar.min()

0

In [76]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [81]:
np.where(ar<4)

(array([0, 0, 0, 2, 2], dtype=int64), array([0, 1, 2, 1, 2], dtype=int64))

In [82]:
np.count_nonzero(ar)

8

In [83]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [84]:
ar[1,2]=0

In [85]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [86]:
import sys

In [88]:
py_ar = [0,4,55,2]

In [89]:
np_ar = np.array(py_ar)

In [90]:
sys.getsizeof(1)*len(py_ar)

112

In [91]:
np_ar.itemsize * np_ar.size

16